Import('env', 'object_files')

libprotobuf = File('/usr/lib/libprotobuf.a')
libcryptopp = File('/usr/lib/libcrypto++.a')
libsnappy = File('/usr/lib/libsnappy.a')
libjemalloc = File('#/jemalloc-4.4.0/lib/libjemalloc.a')
librocksdb = File('#/rocksdb-5.2.1/librocksdb.a')

libs = [ "pthread", libprotobuf, "rt", librocksdb, libcryptopp, libjemalloc, "lz4", "z", "bz2", "snappy"]

src = [
    "Backoff.cc",
    "Client.cc",
    "ClientImpl.cc",
    "LeaderRPC.cc",
    "MockClientImpl.cc",
    "SessionManager.cc",
    "Util.cc",
]
object_files['Client'] = env.StaticObject(src)

env.Default([
    env.Program("ServerControl",
                (["ServerControl.cc", "#build/liblogcabin.a"]),
                LIBS = libs),
])
