Import('env')

libprotobuf = File('/usr/lib/libprotobuf.a')
libcryptopp = File('/usr/lib/libcrypto++.a')
libsnappy = File('/usr/lib/libsnappy.a')
libjemalloc = File('#/jemalloc-4.4.0/lib/libjemalloc.a')
librocksdb = File('#/rocksdb-5.2.1/librocksdb.a')

libs = [ "pthread", libprotobuf, "rt", librocksdb, libcryptopp, libjemalloc, "lz4", "z", "bz2", "snappy"]

env.Default([
    env.Program("Benchmark",
                ["Benchmark.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("FailoverTest",
                ["FailoverTest.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("HelloWorld",
                ["HelloWorld.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("Reconfigure",
                ["Reconfigure.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("ReconfigureTest",
                ["ReconfigureTest.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("SmokeTest",
                ["SmokeTest.cc", "#build/liblogcabin.a"],
                LIBS = libs),

    env.Program("TreeOps",
                ["TreeOps.cc", "#build/liblogcabin.a"],
                LIBS = libs),
])
